spring.datasource.url=jdbc:postgresql://localhost:5432/car_rental
spring.datasource.username=postgres
spring.datasource.password=Dima228*

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=zX8mP2kL9nQ4rT7vW1yE5aH8cK3nR6uV9xZ2bE7fJ1mP4qT8wX3cK6nR9uV2
jwt.expiration-ms=86400000
